version: "3.9"
services: 
  db:
    image: mysql:5.6
    container_name: docker-mysql-hotel
    environment:
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MYSQL_ROOT_PASSWORD: dolibarr
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default
    # networks:
    #   net_server:
    #     aliases:
    #      - mysql_alias
  

  php: 
    build:
      context: ./
      dockerfile: DockerFile
    container_name: servidor_php_hotel
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./dolibarr:/var/www/html
    environment:
        DOLI_DB_HOST: db
        DOLI_DB_USER: admin
        DOLI_DB_PASSWORD: 12345678
        DOLI_DB_NAME: dolibarr
        DOLI_URL_ROOT: 'http://0.0.0.0'
        PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
    links:
       - db:db

    networks:
      - default
    # networks:
    #   net_server:
    #     aliases:
    #        - php_alias
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
          MYSQL_DATABASE: dolibarr
          MYSQL_USER: dolibarr
          MYSQL_PASSWORD: dolibarr
          MYSQL_ROOT_PASSWORD: dolibarr
 
volumes:
  html: {}
  data:
# networks:
#   net_server:
#     name: test
#     driver: bridge
#     ipam: 
#       driver: default